@startuml model
package Domain {

    class 支払い計算結果 {
        - 全参加者支払い金額
        - 不足金額
    }

    class 金額 {
        + 金額 加える(金額)
        + 金額 減ずる(金額)
        + 金額 乗ずる(int)
        + 金額 除する(int)
        + 金額 除したあまり(int)
    }

    class 請求金額 {
        - 金額
        + 支払い最小単位調整前支払い単位金額 除す(全参加者支払い割合)
        + 不足金額 減ずる(全参加者支払い金額)
    }

    class 全参加者支払い金額 {
        - 金額
        + 全参加者支払い金額 変更する(支払い区分別参加者支払い金額)
    }

    class 支払い区分別参加者支払い金額 {
        - 金額
    }

    class 不足金額 {
        - 金額
    }

    class 支払い最小単位調整前支払い単位金額 {
        - 金額
        + 支払い最小単位係数 除す(支払い最小単位)
    }

    class 支払い最小単位調整後支払い単位金額 {
        - 金額
    }

    class 支払い最小単位 {
        - 金額
    }

    class 支払い最小単位係数 {
    }
        
    enum 支払い区分 {
        多め
        普通
        少な目
    }

    class 支払い割合 {
    }

    class 支払い区分別支払い割合設定 {
        - 支払い区分
        - 支払い割合
    }

    class 全支払い区分別支払い割合設定 {
        + 変更 全支払い区分別支払い割合設定(支払い区分別支払い割合設定)
    }

    class 支払い区分別参加者支払い割合 {
        - 支払い区分
        - 支払い割合
    }

    class 全参加者支払い割合 {
        + 変更 全参加者支払い割合(支払い区分別支払い割合)
    }

    class 飲み会 {
        - 請求金額
        - 全参加人数
        - 支払い区分別支払い割合設定
        支払い計算結果 支払い計算する()
    }

    class 参加人数 {
    }

    class 支払い区分別参加人数 {
        - 支払い区分
        - 参加人数
    }

    class 全参加人数 {
        + 全参加人数 変更(支払い区分別参加人数)
    }
}

支払い計算結果 --> 全参加者支払い金額
支払い計算結果 --> 不足金額

請求金額 --> 支払い最小単位調整前支払い単位金額
請求金額 --> 全参加者支払い割合
請求金額 --> 全参加者支払い金額
請求金額 --> 不足金額

支払い区分別参加者支払い金額 --> 支払い最小単位調整後支払い単位金額
支払い区分別参加者支払い金額 --> 支払い区分別参加者支払い割合

全参加者支払い金額 --> 支払い区分別参加者支払い金額

支払い最小単位調整前支払い単位金額 --> 支払い最小単位係数
支払い最小単位調整前支払い単位金額 --> 支払い最小単位

支払い最小単位調整後支払い単位金額 --> 支払い最小単位係数
支払い最小単位調整後支払い単位金額 --> 支払い最小単位

支払い区分別支払い割合設定 --> 支払い区分
支払い区分別支払い割合設定 --> 支払い割合

全支払い区分別支払い割合設定 --> 支払い区分別支払い割合設定

支払い区分別参加者支払い割合 --> 支払い区分
支払い区分別参加者支払い割合 --> 支払い割合

全参加者支払い割合 --> 支払い区分別参加者支払い割合

飲み会 --> 支払い計算結果
飲み会 --> 請求金額
飲み会 --> 全参加人数
飲み会 --> 支払い区分別支払い割合設定

支払い区分別参加人数 --> 支払い区分
支払い区分別参加人数 --> 参加人数

全参加人数 --> 支払い区分別参加人数

請求金額 --> 金額
全参加者支払い金額 --> 金額
支払い区分別参加者支払い金額 --> 金額
不足金額 --> 金額
支払い最小単位調整前支払い単位金額 --> 金額
支払い最小単位調整後支払い単位金額 --> 金額
支払い最小単位 --> 金額
@enduml